endpoint: "0.0.0.0:8080"

tls:
  is_enabled: true
  hostname: beast.jetblack.net
  certfile: /home/rtb/.keys/server.crt
  keyfile: /home/rtb/.keys/server.key

authorization:
  # All users can publish to PUB
  .*:
    "PUB\\..*":
      entitlements:
      - &PUBLIC 0
      roles: Notifier | Publisher | Subscriber
  # Harry is the publisher for LSE data.
  harry:
    "LSE\\..*":
      entitlements:
      - &LSE_LEVEL1 1
      - &LSE_LEVEL2 2
      roles: Notifier | Publisher
  # Harry is the publisher for LSE data.
  freddy:
    "NYSE\\..*":
      entitlements:
      - &NYSE_LEVEL1 3
      - &NYSE_LEVEL2 4
      roles: Notifier | Publisher
  # Tom gets both level 1 and 2 data for LSE and NYSE.
  tom:
    "LSE\\..*":
      entitlements:
      - *LSE_LEVEL1
      - *LSE_LEVEL2
      roles: Subscriber
    "NYSE\\..*":
      entitlements:
      - *NYSE_LEVEL1
      - *NYSE_LEVEL2
      roles: Subscriber
  dick:
    "LSE\\..*":
      entitlements:
      - *LSE_LEVEL1
      roles: Subscriber
    "NYSE\\..*":
      entitlements:
      - *NYSE_LEVEL1
      roles: Subscriber
