endpoint: "0.0.0.0:8080"
tls:
  is_enabled: true
  identity: etc/identity.pfx
authorization:
  # All users can publish to PUB
  .*:
    "PUB\\..*":
      entitlements:
      - 0
      roles: Notifier | Publisher | Subscriber
